apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtsaasapp-deployment
spec:
  selector:
    matchLabels:
      app: gtsaasapp
  replicas: 2
  template:
    metadata:
      labels:
        app: gtsaasapp
    spec:
      containers:
        - name: gtsaasapp
          image: 682033485284.dkr.ecr.us-east-1.amazonaws.com/ecr-gtsaas:latest # Updated image to private DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred # Reference to the Docker registry secret
---
apiVersion: v1
kind: Service
metadata:
  name: gtsaasapp-ssvc
spec:
  selector:
    app: gtsaasapp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer
